//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseManagementv4Code.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CaseMaster()
        {
            this.CaseDetails = new HashSet<CaseDetail>();
        }
    
        public int CaseID { get; set; }
        public int CaseNumber { get; set; }
        public string Agency { get; set; }
        public string Judge { get; set; }
        public System.DateTime FilingDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaseDetail> CaseDetails { get; set; }
    }
}
