//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseManagementv4Code.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CaseDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CaseDetail()
        {
            this.Charges = new HashSet<Charge>();
        }
    
        public int DetailsID { get; set; }
        public int CaseID { get; set; }
        [Required]
        public string DefendantLastName { get; set; }
        [Required]
        public string DefendantFirstName { get; set; }
        [Required]
        public string DefendantAddress { get; set; }
        [Required]
        public string DefendantCity { get; set; }
        [Required]
        public string DefendantState { get; set; }
    
        public virtual CaseMaster CaseMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Charge> Charges { get; set; }
    }
}
