//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseManagementv4Code.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CaseManagementv4Entities : DbContext
    {
        public CaseManagementv4Entities()
            : base("name=CaseManagementv4Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CaseDetail> CaseDetails { get; set; }
        public virtual DbSet<CaseMaster> CaseMasters { get; set; }
        public virtual DbSet<Charge> Charges { get; set; }
    }
}
